### ISSUE TITLE
Add link to RecTrac for programs

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/drupal-module-promt#1]
On the program screen, we should provide a link to RecTrac so people can register.  We only need to do this for programs that are actually in RecTrac.

It also turns out there is no way to craft a URL for RecTrac that will show someone a particular program.  The best we can do is link to the RecTrac (WebTrac) splash page.

**Comment by rbdietz** [comment]
We should request that Parks put in a feature request with Vermont Systems
to provide unique URL registration links for classes/programs.

**Comment by inghamn** [comment]
Added a link in the theming.  The Promt module has no knowledge of RecTrac, so it had to be a COB customization of the twig template.

https://github.com/City-of-Bloomington/drupal-theme-cob/commit/a701baa972bd88b7448ba1954d92a57d3c403567
